export default {
  provider: 'v8',
  reporter: ['text-summary'],
  reportsDirectory: './coverage',
  exclude: [
    'node_modules/**',
    'dist/**',
    'coverage/**',
    '**/*.d.ts',
    '**/*.config.js',
    '**/*.config.ts',
    'src/test/**',
    'src/**/__tests__/**',
    'src/**/*.test.*',
    'src/**/*.spec.*',
    '**/index.ts',
    '**/index.tsx',
    'src/locale/**',
    'src/assets/**',
    'src/styles/**',
    'src/types/**',
    '**/*.stories.*',
    '**/*.mock.*',
    'src/pages/contents/**',
    'src/App/**',
  ],
  include: [
    'src/components/**/*.{ts,tsx}',
    'src/contexts/**/*.{ts,tsx}',
    'src/hooks/**/*.{ts,tsx}',
    'src/config/**/*.{ts,tsx}',
  ],
  thresholds: {
    global: {
      branches: 25,
      functions: 25,
      lines: 25,
      statements: 25,
    },
  },
  all: false,
  skipFull: true,
  clean: false,
  cleanOnRerun: false,
  allowExternal: false,
  enabled: true,
  ignoreClassMethods: [],
  ignoreEmptyLines: true,
  ignoreUnusedLines: true,
  reportOnFailure: false,
  lines: 25,
  functions: 25,
  branches: 25,
  statements: 25,
}
