services:
  fazenda-presentation:
    image: node:20-alpine
    container_name: fazenda-presentation
    ports:
      - ${APP_PORT}:5173
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    command: sh -c "npm install && npm run dev"
    tty: true