version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"   
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/fazendapro_db
    depends_on:
      - mysql
    volumes:
      - .:/app  
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fazendapro_db
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 